/**
 * Synthetic GST Verification Dataset (GSTN / Indirect Taxes)
 * DISCLAIMER: All data in this file is purely SYNTHETIC / FICTIONAL for prototype demonstration.
 */

const SYNTHETIC_GST_RECORDS = [
  {
    gstin: '29SYNPA0001C1Z5',
    legalName: 'ABC Safety Technologies Private Limited',
    tradeName: 'ABC Safety Solutions',
    panNumber: 'SYNPA0001C',
    stateCode: '29',
    state: 'Karnataka',
    registrationDate: '2018-07-01',
    businessType: 'Private Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Jan 2026)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'Manufacturing of Industrial Safety and Protective Equipment',
    registeredAddress: 'Plot 42, Peenya Industrial Area, Phase II, Bengaluru, Karnataka 560058',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '27SYNPA0002L1Z2',
    legalName: 'Apex Safety Solutions LLP', // Differs from PAN legal name (Inconsistency Test)
    tradeName: 'Apex Protect',
    panNumber: 'SYNPA0002L',
    stateCode: '27',
    state: 'Maharashtra',
    registrationDate: '2019-12-15',
    businessType: 'Limited Liability Partnership',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Dec 2025)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'Wholesale of Personal Protective Workwear & Helmets',
    registeredAddress: 'Unit 104, MIDC Industrial Zone, Andheri East, Mumbai, Maharashtra 400093',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '07SYNPA0003P1Z9',
    legalName: 'Zenith Protection Gear & Safety Works',
    tradeName: 'Zenith Safety',
    panNumber: 'SYNPA0003P',
    stateCode: '07',
    state: 'Delhi',
    registrationDate: '2015-05-10',
    businessType: 'Proprietorship',
    taxpayerType: 'Regular',
    registrationStatus: 'SUSPENDED', // GSTIN suspended for return filing default
    filingStatus: 'NON_COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Jun 2024)',
    returnFilingFrequency: 'Quarterly',
    cancellationStatus: 'UNDER_NOTICE',
    principalBusinessActivity: 'Retail and Supply of Industrial Helmets',
    registeredAddress: 'Shop 12, Okhla Industrial Area, Phase I, New Delhi 110020',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '36SYNPA0004C1Z1',
    legalName: 'Paramount Defence Gear Private Limited',
    tradeName: 'Paramount Tactical',
    panNumber: 'SYNPA0004C',
    stateCode: '36',
    state: 'Telangana',
    registrationDate: '2020-02-10',
    businessType: 'Private Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Jan 2026)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'Tactical Protective Gear and Specialized Military Apparel',
    registeredAddress: 'Survey 108, Hardware Park, Shamshabad, Hyderabad, Telangana 501218',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '33SYNPA0005C1Z7',
    legalName: 'Kavach Safety Equipment Manufacturing Limited',
    tradeName: 'Kavach Fall Protection',
    panNumber: 'SYNPA0005C',
    stateCode: '33',
    state: 'Tamil Nadu',
    registrationDate: '2017-09-01',
    businessType: 'Public Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Jan 2026)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'Heavy Duty Harnesses, Lifelines, and Fall Arrest Systems',
    registeredAddress: 'Ambattur Industrial Estate, Chennai, Tamil Nadu 600058',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '19SYNPA0006C1Z4',
    legalName: 'Global Shield Corporation India Private Limited',
    tradeName: 'Global Shield',
    panNumber: 'SYNPA0006C',
    stateCode: '19',
    state: 'West Bengal',
    registrationDate: '2016-05-18',
    businessType: 'Private Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'CANCELLED', // Cancelled GSTIN
    filingStatus: 'DEFAULTED',
    lastReturnFiled: 'GSTR-3B (Mar 2023)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'CANCELLED_BY_DEPT_FRAUD',
    principalBusinessActivity: 'Security Hardware & Safety Equipment',
    registeredAddress: 'Sector V, Salt Lake City, Kolkata, West Bengal 700091',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '27SYNPA0007L1Z8',
    legalName: 'Vanguard Security Works LLP',
    tradeName: 'Vanguard Systems',
    panNumber: 'SYNPA0007L',
    stateCode: '27',
    state: 'Maharashtra',
    registrationDate: '2021-09-15',
    businessType: 'Limited Liability Partnership',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Jan 2026)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'Smart Physical Security and Worksite Safety Systems',
    registeredAddress: 'Hinjawadi Phase 2, Pune, Maharashtra 411057',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '24SYNPA0008C1Z6',
    legalName: 'Reliable Industrial Workwear Private Limited',
    tradeName: 'Reliable Workwear',
    panNumber: 'SYNPA0008C',
    stateCode: '24',
    state: 'Gujarat',
    registrationDate: '2019-03-12',
    businessType: 'Private Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'DELAYED',
    lastReturnFiled: 'GSTR-3B (Nov 2025)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'Fire Retardant Garments and Protective Boots',
    registeredAddress: 'GIDC Estate, Vatva, Ahmedabad, Gujarat 382445',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '06SYNPA0009C1Z3',
    legalName: 'Titan Protective Gears Private Limited',
    tradeName: 'Titan Gears',
    panNumber: 'SYNPA0009C',
    stateCode: '06',
    state: 'Haryana',
    registrationDate: '2014-11-20',
    businessType: 'Private Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'CANCELLED',
    filingStatus: 'DEFAULTED',
    lastReturnFiled: 'GSTR-3B (Jan 2024)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'CANCELLED_ON_APPLICATION',
    principalBusinessActivity: 'Heavy Machinery Protective Guards',
    registeredAddress: 'Udyog Vihar Phase 4, Gurugram, Haryana 122016',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    gstin: '08SYNPA0010C1Z0',
    legalName: 'Shree Ram Industrial Supplies Private Limited',
    tradeName: 'Shree Ram Supplies',
    panNumber: 'SYNPA0010C',
    stateCode: '08',
    state: 'Rajasthan',
    registrationDate: '2015-08-01',
    businessType: 'Private Limited Company',
    taxpayerType: 'Regular',
    registrationStatus: 'ACTIVE',
    filingStatus: 'COMPLIANT',
    lastReturnFiled: 'GSTR-3B (Jan 2026)',
    returnFilingFrequency: 'Monthly',
    cancellationStatus: 'NONE',
    principalBusinessActivity: 'General Industrial & Safety Supplies',
    registeredAddress: 'VKIA Industrial Area, Jaipur, Rajasthan 302013',
    verificationSource: 'SYNTHETIC_GSTN_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
];

module.exports = {
  SYNTHETIC_GST_RECORDS,
  findGstRecord: (gstin) => {
    if (!gstin) return null;
    const cleanGst = gstin.trim().toUpperCase();
    return SYNTHETIC_GST_RECORDS.find(r => r.gstin === cleanGst) || null;
  },
  findGstByPan: (pan) => {
    if (!pan) return null;
    const cleanPan = pan.trim().toUpperCase();
    return SYNTHETIC_GST_RECORDS.find(r => r.panNumber === cleanPan) || null;
  }
};
