/**
 * Synthetic Income Tax / Direct Tax Compliance Dataset (CBDT / CPC)
 * DISCLAIMER: All data in this file is purely SYNTHETIC / FICTIONAL for prototype demonstration.
 */

const SYNTHETIC_INCOME_TAX_RECORDS = [
  {
    panNumber: 'SYNPA0001C',
    legalName: 'ABC Safety Technologies Private Limited',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-10-18',
    filingStatus: 'FILED_VERIFIED',
    itrType: 'ITR-6',
    grossTotalIncome: 48500000,
    taxComplianceStatus: 'COMPLIANT',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0002L',
    legalName: 'Apex Industrial Protective Equipments LLP',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-10-24',
    filingStatus: 'FILED_VERIFIED',
    itrType: 'ITR-5',
    grossTotalIncome: 9200000,
    taxComplianceStatus: 'COMPLIANT',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0003P',
    legalName: 'Zenith Protection Gear & Safety Works',
    assessmentYear: '2025-26',
    returnFiled: false, // Defaulted on return filing
    filingDate: null,
    filingStatus: 'RETURN_PENDING',
    itrType: 'ITR-3',
    grossTotalIncome: 0,
    taxComplianceStatus: 'NON_COMPLIANT',
    outstandingDemand: 450000, // INR 4.5 Lakhs outstanding demand
    taxRegistrationStatus: 'INACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0004C',
    legalName: 'Paramount Defence Gear Private Limited',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-09-30',
    filingStatus: 'FILED_VERIFIED',
    itrType: 'ITR-6',
    grossTotalIncome: 245000000,
    taxComplianceStatus: 'COMPLIANT',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0005C',
    legalName: 'Kavach Safety Equipment Manufacturing Limited',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-10-15',
    filingStatus: 'FILED_VERIFIED',
    itrType: 'ITR-6',
    grossTotalIncome: 380000000,
    taxComplianceStatus: 'COMPLIANT',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0006C',
    legalName: 'Global Shield Corporation India Private Limited',
    assessmentYear: '2025-26',
    returnFiled: false,
    filingDate: null,
    filingStatus: 'NON_FILER',
    itrType: 'ITR-6',
    grossTotalIncome: 0,
    taxComplianceStatus: 'NON_COMPLIANT_DEMAND_PENDING',
    outstandingDemand: 18500000, // INR 1.85 Cr recovery notice
    taxRegistrationStatus: 'SUSPENDED',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0007L',
    legalName: 'Vanguard Security Works LLP',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-10-28',
    filingStatus: 'FILED_VERIFIED',
    itrType: 'ITR-5',
    grossTotalIncome: 14200000,
    taxComplianceStatus: 'COMPLIANT',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0008C',
    legalName: 'Reliable Industrial Workwear Private Limited',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-11-10',
    filingStatus: 'FILED_LATE',
    itrType: 'ITR-6',
    grossTotalIncome: 52000000,
    taxComplianceStatus: 'COMPLIANT_WITH_PENALTY_PAID',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0009C',
    legalName: 'Titan Protective Gears Private Limited',
    assessmentYear: '2025-26',
    returnFiled: false,
    filingDate: null,
    filingStatus: 'NON_FILER',
    itrType: 'ITR-6',
    grossTotalIncome: 0,
    taxComplianceStatus: 'DEFAULTED',
    outstandingDemand: 6200000,
    taxRegistrationStatus: 'INACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0010C',
    legalName: 'Shree Ram Industrial Supplies Private Limited',
    assessmentYear: '2025-26',
    returnFiled: true,
    filingDate: '2025-10-05',
    filingStatus: 'FILED_VERIFIED',
    itrType: 'ITR-6',
    grossTotalIncome: 18000000,
    taxComplianceStatus: 'COMPLIANT',
    outstandingDemand: 0,
    taxRegistrationStatus: 'ACTIVE',
    verificationSource: 'SYNTHETIC_CBDT_ITR_GATEWAY',
    lastVerifiedAt: new Date().toISOString(),
  },
];

module.exports = {
  SYNTHETIC_INCOME_TAX_RECORDS,
  findTaxRecord: (pan) => {
    if (!pan) return null;
    const cleanPan = pan.trim().toUpperCase();
    return SYNTHETIC_INCOME_TAX_RECORDS.find(r => r.panNumber === cleanPan) || null;
  }
};
