/**
 * Synthetic PAN Verification Dataset (CBDT / Income Tax Department)
 * DISCLAIMER: All data in this file is purely SYNTHETIC / FICTIONAL for prototype demonstration.
 * No real personal or corporate identities are utilized.
 */

const SYNTHETIC_PAN_RECORDS = [
  {
    panNumber: 'SYNPA0001C',
    legalName: 'ABC Safety Technologies Private Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2018-06-15',
    status: 'ACTIVE',
    jurisdiction: 'Ward 3(2), Bengaluru, Karnataka',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0002L',
    legalName: 'Apex Industrial Protective Equipments LLP',
    entityType: 'LLP',
    dateOfIncorporation: '2019-11-20',
    status: 'ACTIVE',
    jurisdiction: 'Ward 12(1), Mumbai, Maharashtra',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'PARTIAL_MATCH', // Name on GST differs slightly
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0003P',
    legalName: 'Zenith Protection Gear & Safety Works',
    entityType: 'PROPRIETORSHIP',
    dateOfIncorporation: '2015-03-10',
    status: 'INACTIVE', // Inactive PAN test case
    jurisdiction: 'Ward 5(4), New Delhi',
    assessmentYear: '2024-25',
    panActive: false,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0004C',
    legalName: 'Paramount Defence Gear Private Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2020-01-14',
    status: 'ACTIVE',
    jurisdiction: 'Ward 8(3), Hyderabad, Telangana',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0005C',
    legalName: 'Kavach Safety Equipment Manufacturing Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2017-08-22',
    status: 'ACTIVE',
    jurisdiction: 'Ward 4(1), Chennai, Tamil Nadu',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0006C',
    legalName: 'Global Shield Corporation India Private Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2016-04-22',
    status: 'ACTIVE',
    jurisdiction: 'Ward 1(1), Kolkata, West Bengal',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0007L',
    legalName: 'Vanguard Security Works LLP',
    entityType: 'LLP',
    dateOfIncorporation: '2021-08-30',
    status: 'ACTIVE',
    jurisdiction: 'Ward 6(2), Pune, Maharashtra',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0008C',
    legalName: 'Reliable Industrial Workwear Private Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2019-02-18',
    status: 'ACTIVE',
    jurisdiction: 'Ward 9(4), Ahmedabad, Gujarat',
    assessmentYear: '2025-26',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0009C',
    legalName: 'Titan Protective Gears Private Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2014-10-05',
    status: 'SURRENDERED',
    jurisdiction: 'Ward 2(1), Gurugram, Haryana',
    assessmentYear: '2023-24',
    panActive: false,
    nameMatchStatus: 'NAME_MISMATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    panNumber: 'SYNPA0010C',
    legalName: 'Shree Ram Industrial Supplies Private Limited',
    entityType: 'COMPANY',
    dateOfIncorporation: '2015-07-07',
    status: 'ACTIVE',
    jurisdiction: 'Ward 11(3), Jaipur, Rajasthan',
    assessmentYear: '2024-25',
    panActive: true,
    nameMatchStatus: 'EXACT_MATCH',
    verificationSource: 'SYNTHETIC_CBDT_DATASET',
    lastVerifiedAt: new Date().toISOString(),
  },
];

module.exports = {
  SYNTHETIC_PAN_RECORDS,
  findPanRecord: (pan) => {
    if (!pan) return null;
    const cleanPan = pan.trim().toUpperCase();
    return SYNTHETIC_PAN_RECORDS.find(r => r.panNumber === cleanPan) || null;
  }
};
